apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "nginx"
  name: "nginx"
spec:
  replicas: 1
  selector:
    app: "nginx"
    deploymentconfig: "nginx"
  template:
    metadata:
      labels:
        app: "nginx"
        deploymentconfig: "nginx"
    spec:
      containers:
        - env:
          - name: HELLO
            value: "KITTY"
          image: 'docker.io/nginx:latest'
          imagePullPolicy: Always
          name: "nginx"
          ports:
          - containerPort: 8443
            name: nginx
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: nginx
            subPath: nginx.conf
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx
            subPath: default.conf
          - mountPath: /homepage/index.html
            name: nginx
            subPath: index.html
      volumes:
        - name: nginx
          configMap:
            name: nginx
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - "nginx"
        from:
          kind: ImageStreamTag
          name: "nginx:latest"
        lastTriggeredImage: 'docker.io/nginx:latest'
      type: ImageChange


