apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "nginx"
  name: "nginx"
spec:
  replicas: 1
  selector:
    app: "nginx"
    deploymentconfig: "nginx"
  template:
    metadata:
      labels:
        app: "nginx"
        deploymentconfig: "nginx"
    spec:
      containers:
      - image: 'docker.io/nginx:latest'
        imagePullPolicy: Always
        name: "nginx"
        ports:
        - containerPort: 8443
          name: nginx
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-conf
          subPath: default.conf
        - mountPath: /homepage
          name: nginx-homepage
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-homepage
          configMap:
            name: nginx-homepage
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - "nginx"
        from:
          kind: ImageStreamTag
          name: "nginx:latest"
        lastTriggeredImage: 'docker.io/nginx:latest'
      type: ImageChange


